# Generated by Django 6.0.1 on 2026-02-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_order_total_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Foods', 'Foods'), ('Items', 'Items'), ('Gadgets', 'Gadgets'), ('Furnitures', 'Furnitures'), ('Accessories', 'Accessories'), ('Clothes', 'Clothes'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
